POST http://localhost:3000/chosen-cigarettes HTTP/1.1
content-type: application/json

{
    "data": [
        {
            "flavour": "Full",
            "size": "KS/25",
            "quantity": "1",
            "name": "Pall Mall"
        },
        {
            "flavour": "Full",
            "size": "KS/25",
            "quantity": "13",
            "name": "Pall Mall"
        }
    ]
}